name: medmodv2
channels:
- conda-forge
- defaults
dependencies:
- python=3.12
- virtualenv>=20.20.0
- pip>=20.0
- poetry>=1.8
- _libgcc_mutex
- _openmp_mutex
- blas
- bzip2
- ca-certificates
- cairo
- cudatoolkit
- dbus
- expat
- ffmpeg
- fontconfig
- freeglut
- freetype
- glib
- gmp
- gnutls
- graphite2
- gst-plugins-base
- gstreamer
- harfbuzz
- hdf5
- icu
- intel-openmp
- jasper
- jpeg
- lcms2
- ld_impl_linux-64
- libblas
- libcblas
- libedit
- libffi
- libgcc-ng
- libgfortran
- libgfortran-ng
- libglu
- libiconv
- liblapack
- libopencv
- libopus
- libpng
- libprotobuf
- libsodium
- libstdcxx-ng
- libtiff
- libuuid
- libuv
- libvpx
- libxcb
- libxml2
- libzlib
- llvm-openmp
- lz4-c
- mkl
- nb_conda
- nb_conda_kernels
- ncurses
- nettle
- ninja
- ninja-base
- openh264
- openssl
- pandoc
- pcre
- pixman
- pthread-stubs
- qt
- readline
- sqlite
- tk
- x264
- xorg-fixesproto
- xorg-inputproto
- xorg-kbproto
- xorg-libx11
- xorg-libxau
- xorg-libxdmcp
- xorg-libxext
- xorg-libxfixes
- xorg-libxi
- xorg-xextproto
- xorg-xproto
- xz
- zeromq
- zlib
- zstd
