[tool.poetry]
name = "medmod"
version = "0.1.0"
description = ""
authors = ["Author <author@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"
PyQt5 = "*"
PyYAML = "*"
absl-py = "*"
aiohttp = "*"
aiosignal = "*"
argon2-cffi = "*"
async-timeout = "*"
asynctest = "*"
attrs = "*"
backcall = "*"
"backports.functools_lru_cache" = "*"
bleach = "*"
blinker = "*"
boto3 = "*"
botocore = "*"
bravado = "*"
bravado-core = "*"
brotli = "*"
cachetools = "*"
certifi = "*"
cffi = "*"
chardet = "*"
charset-normalizer = "*"
click = "*"
cloudpickle = "*"
contextvars = "*"
cryptography = "*"
cycler = "*"
decorator = "*"
defusedxml = "*"
docstring-parser = "*"
entrypoints = "*"
frozenlist = "*"
fsspec = "*"
future = "*"
fuzzywuzzy = "*"
gitdb = "*"
gitpython = "*"
google-auth = "*"
google-auth-oauthlib = "*"
grpcio = "*"
h5py = "*"
idna = "*"
idna-ssl = "*"
immutables = "*"
importlib-metadata = "*"
importlib-resources = "*"
ipykernel = "*"
ipython = "*"
ipython-genutils = "*"
ipywidgets = "*"
jedi = "*"
jinja2 = "*"
jmespath = "*"
joblib = "*"
jsonargparse = "*"
jsonref = "*"
jsonschema = "*"
jupyter-client = "*"
jupyter-core = "*"
jupyterlab-pygments = "*"
jupyterlab-widgets = "*"
keras = "*"
kiwisolver = "*"
lightning-flash = "*"
markdown = "*"
markupsafe = "*"
matplotlib = "*"
mistune = "*"
mock = "*"
monotonic = "*"
msgpack = "*"
multidict = "*"
nbclient = "*"
nbconvert = "*"
nbformat = "*"
neptune-client = "*"
nest-asyncio = "*"
networkx = "*"
notebook = "*"
numpy = "*"
oauthlib = "*"
olefile = "*"
opencv-python = "*"
packaging = "*"
pandas = "*"
pandocfilters = "*"
parso = "*"
pexpect = "*"
pickleshare = "*"
pillow = "*"
prometheus-client = "*"
prompt-toolkit = "*"
protobuf = "*"
psutil = "*"
ptyprocess = "*"
py3nvml = "*"
pyasn1 = "*"
pyasn1-modules = "*"
pycparser = "*"
pydeprecate = "*"
pygments = "*"
pyjwt = "*"
pyopenssl = "*"
pyparsing = "*"
pyrsistent = "*"
pysocks = "*"
python-dateutil = "*"
pytorch-lightning = "*"
pytz = "*"
pyzmq = "*"
requests = "*"
requests-oauthlib = "*"
rsa = "*"
s3transfer = "*"
scikit-learn = "*"
scipy = "*"
send2trash = "*"
simplejson = "*"
sip = "*"
six = "*"
smmap = "*"
swagger-spec-validator = "*"
tensorboard = "*"
tensorboard-data-server = "*"
tensorboard-plugin-wit = "*"
tensorflow = "*"
terminado = "*"
testpath = "*"
threadpoolctl = "*"
torch = "*"
torchaudio = "*"
torchmetrics = "*"
torchvision = "*"
tornado = "*"
tqdm = "*"
traitlets = "*"
typeshed-client = "*"
typing-extensions = "*"
urllib3 = "*"
warmup-scheduler = "*"
wcwidth = "*"
webencodings = "*"
websocket-client = "*"
werkzeug = "*"
widgetsnbextension = "*"
xmltodict = "*"
yarl = "*"
zipp = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
